### PR TITLE
Bail application form

### PR DESCRIPTION
**Pull request by pnvt29**
I add Bail Application form. Here is what it looks like.
Screen Shot 2019-04-29 at 4 14 33 PM

### CODE REVIEW

**Comment by autumnwoz** [comment]
Depending on how busy you are tonight, G expressed interest in seeing what different input types looked like so you could add in some examples of radio buttons, drop downs, checkboxes, etc.  You can use basic things like gender (drop down) or if they're filling out the form for themselves or for someone else (radio button) to do this.

**Comment by pnvt29** [comment]
> Depending on how busy you are tonight, G expressed interest in seeing what different input types looked like so you could add in some examples of radio buttons, drop downs, checkboxes, etc. You can use basic things like gender (drop down) or if they're filling out the form for themselves or for someone else (radio button) to do this.

**Comment by pnvt29** [comment]
> Depending on how busy you are tonight, G expressed interest in seeing what different input types looked like so you could add in some examples of radio buttons, drop downs, checkboxes, etc. You can use basic things like gender (drop down) or if they're filling out the form for themselves or for someone else (radio button) to do this.

**Comment by pnvt29** [comment]
I added radio button and drop down
Screen Shot 2019-04-29 at 6 46 41 PM

**Review by autumnwoz — APPROVED** [review]

**Pull request merged**
